# Site settings
# title: "Acr Ev"
# description: "nome evento completo"
#url: "/" # the base hostname & protocol for your site
title: "Tiqit"
description: "Tiqit"
url: "https://ai-sf.it/tiqit24"
destination: ../site/
locale: "it"

# Build settings
markdown: kramdown
future: true
permalink: /blog/:year/:month/:day/:title/
destination: _site


#facebook
fb_admins:
fb_appid:

#Collections
collections:
  events:
    output: true
    permalink: /:categories/:year/:month/:day/:title/

gems:
 - jekyll-redirect-from
 - jekyll-sitemap
